services:
  - type: web
    name: firstdivision
    env: static
    buildCommand: "build"
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
