services:
  - type: web
    name: firstdivision
    env: static
    buildCommand: "" # No build step needed
    staticPublishPath: public # Remove the ./ prefix
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 
