services:
  - type: web
    name: firstdivision
    env: static
    buildCommand: "mkdir -p public" # Ensure public directory exists
    staticPublishPath: public
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
