services:
  - type: web
    name: firstdivision
    env: static
    buildCommand: "cp -r public/* ." # Copy contents from public to root
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
