services:
  - type: web
    name: firstdivision
    env: static
    buildCommand: "" # No build step needed
    staticPublishPath: Public # Change to your actual folder
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
